### ISSUE TITLE
help.

### ISSUE THREAD

**Issue by Lulz231** [tdammers/E-jet-family-YV#14]
idk if i'm writing in the right place, But when ever i try to spawn in one of the E-Jet aircraft it freezes in loading and then flight gear closes.

**Comment by sfrsfrsfr** [comment]
no, this is not exactly the right place for support questions. pls post your question/problem on the [https://forum.flightgear.org](Forum) or join our [Discord](https://discord.gg/rzuV2DR) in either case you need to provide more information. FG version, your hw setup etc. you might also try other aircrafts like the Cessna c172p that comes with flightgear.

sfr
