### ISSUE TITLE
Livery Contributions

### ISSUE THREAD

**Issue by sriemmanuel787** [tdammers/E-jet-family-YV#21]
Hello Mr.Dammers,

I have been interested in this aircraft for a long time, and I want to make some liveries for this aircraft in 4K resolution. If I made these liveries, how would I be able to contribute these liveries to this repository?

Also, I was wondering if the LR variant is on the schedule anytime soon. I think the main difference is that the LR has larger, flatter winglets.

**Comment by tdammers** [comment]
Sorry for not getting back to you earlier, your messages (both here and on the FG forums) seem to have slipped through.

Anyway, to answer your questions:

The liveries look great; I'll try them on the real thing, and if they look as good in 3D as they do in 2D, I'll happily merge them. I just need you to answer two questions:

- Did you use any third-party materials in the creation of these liveries, or were they made from scratch? This is important for copyright reasons.
- Do you agree to releasing these liveries under the GNU GPL version 2.0 or later, or a compatible open-source license?

Then; I have no plans for an LR version (yet), but if you want to take a stab at modelling the winglets, and can provide some data on the performance differences, I'll be happy to make the LR variants a thing. It's not that I don't want them, just that I'm not good at 3D modelling at all. Keep in mind though that CaptB has a cockpit remodelling in the pipeline that may also affect the exterior model, so conflicts may or may not arise from this.

**Comment by tdammers** [comment]
Quick update: they look stunning in the sim.

**Comment by sriemmanuel787** [comment]
I did create them from scratch, and they are available under GNU GPL.
